site_name: csH Java docs
site_description: 'supporting csH Java at stkentac'
site_author: 'B McCart'
docs_dir: docs/
repo_name: 'compstki/csHjavaDocs'
repo_url: 'https://github.com/compstki/csHjavaDocs'
nav:
    - Home: index.md
    - crypto: crypto.md
theme:
  name: 'readthedocs'
